---
title: "Lab 5"
author: "Drew Hoffman, Tanner Ball, Burke Parent, David Washburn, Brandon Nelsen"
date: "9/27/2019"
output: html_document
---

```{r}
# Load tidyverse
library(tidyverse)

# Load and view the data
milk <- read.csv('state_milk_production.csv')
head(milk)

# Add a column for millions of milk pounds
milk <- milk %>%
  mutate(milk_million = milk_produced/1000000)
```

**Team Section:**

**Arizona, California, Colorado, Illinois, and Texas**

```{r, echo=FALSE}
milksub <- milk %>%
  filter(state %in% c('Arizona','California','Colorado','Illinois','Texas')) %>%
  select(state, year, milk_million)

milkavg <- milk %>% select(year, milk_million) %>% group_by(year) %>% summarise(avg = sum(milk_million)/50)

ggplot() +
  geom_point(data = milksub, aes(x = year, y = milk_million, color = state)) + 
  ggtitle('Pounds of milk over time by state') +
  xlab('Year') +
  ylab('Milk Produced (Million lb)') +
  geom_smooth(data=milkavg, aes(x=year, y=avg), color='black')
```

**Information That the Plot Conveys:**


Year of most milk production:

Year of least milk production:

2017 5 states with most milk:

2017 5 states with least milk:

**Individual Sections**

**Drew:**

```{r, echo=FALSE}

```

**Brandon:**

```{r, echo=FALSE}

```

**David:**

```{r, echo=FALSE}

```

**Tanner:**

```{r, echo=FALSE}
test
```

**Burke:**

```{r, echo=FALSE}

```

**Most helpful thing:**


**Ethical Analysis**

